spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - StripPrefix=1
      routes:
        - id: postcode-service
          uri: http://localhost:8071/postcode-service
          predicates:
            - Path=/postcode-service/**
        - id: distance-service
          uri: http://localhost:8072/distance-service
          predicates:
            - Path=/distance-service/**

server:
  port: 8070


app:
  username: user
  password: password
  role: USER
