spring:
  application:
    name: distance-service
  cloud:
    discovery:
      client:
        simple:
          instances:
            postcode-service:
              - uri: http://localhost:8071

server:
  port: 8072


